# Generated by Django 5.2.7 on 2026-06-16 16:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_registration_options_registration_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='ticket_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
