# Generated by Django 5.2.7 on 2026-07-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_registration_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='amount_paid',
            new_name='amount_to_pay',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='ticket_code',
        ),
        migrations.AddField(
            model_name='registration',
            name='order_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
